### PR TITLE
add form invalid message feature, inject custom service into directive.

### PR DESCRIPTION
**Pull request by codonist**
Hi there, 

I enable invalid-message attribute on form element, so that we do not need to specify invalid-message on each field. The value of invalid-message on form should be an angular service which has a function named `message`. In the message function, customized messages are managed based on $error of specific field. There are no major changes in angular-validator.js. I just add `hasFormInvalidMessage` function and update a little bit `setupWatch` and `updateValidationMessage`. 

Thanks. 
Best regards

### CODE REVIEW

**Comment by Jakobovski** [comment]
Hey thanks for your contribution. It looks good! You changed the indentation on the code so I cant see what you changed as it shows every line has having been changed. Can you please make sure your code uses 4 spaces for indentation and not tabs and then commit your changes. Thanks!

**Comment by codonist** [comment]
Hi there,

Sorry about the indents. I have fixed them. If there is any other problems, please do not hesitate to tell me. Thank you very much!

**Comment by Jakobovski** [comment]
Thanks. I have been super busy. I will try to take a look at this in the next few days.

**Comment by Jakobovski** [comment]
This looks really good!  Can you please fix merge conflicts and then I will merge it :)

**Comment by codonist** [comment]
Hi there,
Just fix the conflict and also update karma version from ~0.12.1 to ^0.13.0 in order for travis to pass. 
If there is any other problems, please do not hesitate to contact me. 
Thanks :)

**Pull request merged**
