### PR TITLE
Add async support to angular validator

### PR DESCRIPTION
**Pull request by Jakobovski**

### CODE REVIEW

**Comment by Jakobovski** [comment]
When you are ready would you like to have this merged into angular-validator?

**Comment by marcelinhov2** [comment]
OMG you gonna do this merge today? 

I really need it, can I help with something?

**Comment by Jakobovski** [comment]
@marcelinhov2 It depends if @ball6847  is ready for it to be merged...

**Comment by marcelinhov2** [comment]
it will have $resource support?

**Comment by ball6847** [comment]
@marcelinhov2 it does support $resource , just make sure you return $promise in the callback.

**Pull request closed without merging**
