### PR TITLE
Added custom error elements

### PR DESCRIPTION
**Pull request by wulftone**
For issue https://github.com/turinggroup/angular-validator/issues/17.

See additions to README for details

### CODE REVIEW

**Comment by Jakobovski** [comment]
Overall this looks good! Can you create a new plunker that demonstrates your changes and then change the demo url in the `readme` to the new plunker? I will test and then merge.

Although you have already done the work, you also might want to take a look at this: https://docs.angularjs.org/api/ngMessages/directive/ngMessages. One of the advantages of ngMessages is it allows for the CSS to be controlled on a per message basis. Ex. success text might be green and error text red.  There is an additional advantage of it working with the standard angular validation directives such as `ng-minlength`... 

All that being said I am still happy to merge your changes as is.

**Comment by wulftone** [comment]
Good point, I'll fiddle with that and see what it's all about.  I'm playing with the plunker right now :)

**Comment by wulftone** [comment]
There are some errors, I'll fix them after work.

**Comment by Jakobovski** [comment]
Awesome. Thanks for all your work on this.

**Comment by wulftone** [comment]
Should be ready to roll now

**Comment by Jakobovski** [comment]
@wulftone 

I apologize for taking so long to get back to you.  I have been procrastinating on this is because I have been questioning wether custom error messages should be implemented using your approach or using ngMessages. 

I have come to the conclusion that custom error messages should use the ngMessages directive as mentioned above.  Would you be interested in implementing this instead? 

Thanks for all your work on this.

**Comment by wulftone** [comment]
No worries, at the time, we weren't using angular 1.3, so ngMessages wasn't
an option for us. I'd like to do it, but I don't know if I'll be able to
get to it anytime soon. If someone else has a more pressing need, I
encourage them to take up the banner. : )

**Comment by Jakobovski** [comment]
Sounds good. Thanks

**Pull request closed without merging**
